defaults:
  - data: sim_ir
  - system: jirvis
  - _self_

user: root

seed: 42
process_title: jirvis-training

output_dir: ./logs/${system.name}/${data.name}

# You must specify this
data_root: ./data/sample/
load_system_checkpoint: ./data/jirvis.pt # for testing model
mode: train

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:${device.id}
