defaults:
  - data: sim_ir
  - system: jirvis
  - _self_

user: root

seed: 42
process_title: jirvis-inference

output_dir: ./inference/${system.name}/${data.name}

# You must specify this
data_root: ./data/sample/
load_system_checkpoint: ./data/jirvis.pt

mode: inference

device:
  cuda_visible_devices:  "0,1,2,3,4,5,6"
  id: 0
  cuda: cuda:${device.id}


model:
  name: resnet
  arch:
    _target_: jirvis.models.resnet50.ResNetFeatureExtractor
    num_labels: 25                                    # overwritten by system.data.label_indices
    model_name: R50                                   # R18, R34, R50, R101, R152
    model_type: 4_layer                               # standard, residual, squeeze, 4_layer
    channels: 3
    pretrained: true                                  # true for ImageNet

data:
  label_indices: [0, 1, 4, 5, 6, 7, 9, 10, 11, 12]    # Which label indices to train on

data:
  # data_root: /home/rudra/Spectro/downloaded/data/final_data/ir_images_simulated/ # DELETE
  data_root: ${data_root}/simulated
  dataset: sim_ir
  batch_size: 16
  num_workers: 3
  is_grayscale: True
  use_catch_all: False
  split_ratio: [0.7, 0.2, 0.1]
